# Generated by Django 3.0.5 on 2020-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='addr_link',
            field=models.URLField(default='#'),
        ),
    ]
