# Generated by Django 3.0.5 on 2020-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='other_links',
            field=models.URLField(default='#'),
        ),
    ]
